import type { Metadata } from 'next';
import localFont from 'next/font/local';

// import Provider from '@/src/app/providers/provider';
import './styles/globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const pretendard = localFont({
    src: '../../public/fonts/PretendardVariable.woff2',
    display: 'swap',
    weight: '45 920',
    variable: '--font-pretendard',
});

export default function App({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="kr" className={`${pretendard.variable}`}>
            <body className={`${pretendard.className} `}>
                {/* <Provider>{children}</Provider> */}
                {children}
            </body>
        </html>
    );
}
