import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Script from 'next/script';

import './styles/globals.css';

const pretendard = localFont({
    src: './../../public/fonts/PretendardVariable.woff2',
    variable: '--font-pretendard',
    weight: '45 920',
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const App = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="ko">
            <head>
                <link rel="manifest" href="/manifest.json" />
            </head>
            <body className={`${pretendard.variable} antialiased`}>
                {children}

                {/* Google Analytics */}
                <Script strategy="afterInteractive" src="https://www.googletagmanager.com/gtag/js?id=G-60E91B6QPQ" />
                <Script id="google-analytics" strategy="afterInteractive">
                    {`
                        window.dataLayer = window.dataLayer || [];
                        function gtag(){dataLayer.push(arguments);}
                        gtag('js', new Date());
                        gtag('config', 'G-60E91B6QPQ');
                    `}
                </Script>
            </body>
        </html>
    );
};
