import type { Metadata } from 'next';

// import Provider from '@/src/app/providers/provider';
import './styles/globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function App({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="kr" className={`${pretendard.variable}`}>
            <body className={`${pretendard.className} `}>
                {/* <Provider>{children}</Provider> */}
                {children}
            </body>
        </html>
    );
}
